services:
  web:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - NODE_ENV=development
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
    profiles: ["dev", "default"]

  web-prod:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - NODE_ENV=production
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_APP_DOMAIN=localhost
      - NEXT_PUBLIC_HTTPS_ENABLED=false
    profiles: ["prod"]

# Custom network for better isolation
networks:
  frontend-network:
    driver: bridge
