name: Build and Deploy to Azure

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual triggering

env:
  REGISTRY: 'therickybobbehArc.azurecr.io'  # Your Azure Container Registry name
  WEB_IMAGE_NAME: 'portfolio-frontend'      # Image name for Next.js frontend
  API_IMAGE_NAME: 'portfolio-backend'       # Image name for FastAPI backend
  WEB_APP_NAME: 'portfolio-web'             # Azure App Service name for frontend
  API_APP_NAME: 'portfolio-api'             # Azure App Service name for backend

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.REGISTRY }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      # Build and push frontend image
      - name: Build and push frontend image
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.WEB_IMAGE_NAME }}:${{ github.sha }},${{ env.REGISTRY }}/${{ env.WEB_IMAGE_NAME }}:latest
          cache-from: type=registry,ref=${{ env.REGISTRY }}/${{ env.WEB_IMAGE_NAME }}:latest
          cache-to: type=inline
          build-args: |
            NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL }}

      # Build and push backend image
      - name: Build and push backend image
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.API_IMAGE_NAME }}:${{ github.sha }},${{ env.REGISTRY }}/${{ env.API_IMAGE_NAME }}:latest
          cache-from: type=registry,ref=${{ env.REGISTRY }}/${{ env.API_IMAGE_NAME }}:latest
          cache-to: type=inline
          build-args: |
            DATABASE_URL=${{ secrets.DATABASE_URL }}
            SECRET_KEY=${{ secrets.SECRET_KEY }}
            FRONTEND_URL=${{ secrets.FRONTEND_URL }}

      # Deploy frontend to Azure Web App
      - name: Deploy frontend to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.WEB_APP_NAME }}
          images: ${{ env.REGISTRY }}/${{ env.WEB_IMAGE_NAME }}:${{ github.sha }}

      # Deploy backend to Azure Web App
      - name: Deploy backend to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.API_APP_NAME }}
          images: ${{ env.REGISTRY }}/${{ env.API_IMAGE_NAME }}:${{ github.sha }}