name: Deploy Azure Function

on:
  push:
    branches:
      - main
    paths:
      - 'api/**' # Only run this workflow when API code changes
      - 'frontend/app/utils/chatPrompt.js' # Also run when the shared prompt file changes
  workflow_dispatch: # Allow manual triggering

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22.x'

    - name: Install dependencies
      run: |
        cd api
        # Use npm install instead of npm ci since package-lock.json might not exist
        npm install

    - name: Deploy to Azure Function App
      uses: Azure/functions-action@v1
      with:
        app-name: 'portfolio-api-func'
        slot-name: 'production'
        package: 'api'
        publish-profile: ${{ secrets.AZURE_FUNCTION_PUBLISH_PROFILE }}
        # Uncomment below if you need to set environment variables
        # app-settings-json: ${{ secrets.FUNCTION_APP_SETTINGS }}