name: Build and deploy Docker Compose to Azure Web App

env:
  AZURE_WEBAPP_NAME: development-profile   # Your actual web app name

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write
  id-token: write # This is needed for azure/login

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Lowercase the repo name
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV

      # Build and push frontend container
      - name: Build and push frontend image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: |
            ghcr.io/${{ env.REPO }}/frontend:${{ github.sha }}
            ghcr.io/${{ env.REPO }}/frontend:latest
          file: ./frontend/Dockerfile

      # Create a production docker-compose file with updated image tags
      - name: Generate production docker-compose file
        run: |
          cat <<EOF > docker-compose.production.yml
          version: '3'
          services:
            frontend:
              image: ghcr.io/${{ env.REPO }}/frontend:${{ github.sha }}
              ports:
                - "80:3000"
              environment:
                - NEXT_PUBLIC_API_URL=https://api.yourbackend.com  # Update this to your actual API URL
              restart: always

          volumes:
            postgres_data:
          EOF

      # Upload docker-compose file as artifact
      - name: Upload docker-compose as artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-compose-config
          path: docker-compose.production.yml
          retention-days: 1  # Only keep for 1 day since it's just for deployment

  deploy:
    runs-on: ubuntu-latest
    needs: build

    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Lowercase the repo name
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV

      # Download docker-compose file artifact
      - name: Download docker-compose artifact
        uses: actions/download-artifact@v4
        with:
          name: docker-compose-config
          
      # Log in to Azure
      - name: Log in to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          
      # Deploy to Azure Web App with Docker Compose
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          images: ghcr.io/${{ env.REPO }}/frontend:${{ github.sha }}